name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Tailscale
      shell: powershell
      run: |
        Invoke-WebRequest 'https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe' -OutFile 'tailscale-setup.exe'
        Start-Process 'tailscale-setup.exe' -ArgumentList '/quiet' -Wait
        Start-Sleep -Seconds 5
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey="${{ secrets.TAILSCALE_AUTHKEY }}" --unattended

    - name: Setting RDP & Password
      shell: powershell
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        $Password = ConvertTo-SecureString "P@sswordRDP123!" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $Password

    - name: Keep Alive
      shell: powershell
      run: Start-Sleep -Seconds 21600
