name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Tailscale
      shell: powershell
      run: |
        Invoke-WebRequest 'https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe' -OutFile 'tailscale-setup.exe'
        Start-Process 'tailscale-setup.exe' -ArgumentList '/quiet' -Wait
        Start-Sleep -Seconds 5
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey="${{ secrets.TAILSCALE_AUTHKEY }}" --unattended

    - name: Bikin User RDP
      shell: powershell
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
        
        $Password = ConvertTo-SecureString "P@sswordRDP123!" -AsPlainText -Force
        New-LocalUser -Name "zul" -Password $Password
        Add-LocalGroupMember -Group "Administrators" -Member "zul"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member "zul"

    - name: Keep Alive
      shell: powershell
      run: Start-Sleep -Seconds 21600
