name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ""
        oauth-secret: ""
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Setting RDP & Password
      shell: powershell
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        $Password = ConvertTo-SecureString "P@sswordRDP123!" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $Password

    - name: Keep Alive
      shell: powershell
      run: Start-Sleep -Seconds 21600
